services:
  - type: web
    name: contact-form-api
    runtime: dotnet
    buildCommand: dotnet publish -c Release -o out
    startCommand: dotnet ./out/FormForPF.dll
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: ConnectionStrings__DefaultConnection
        value: Host=...;Port=...;Database=...;Username=...;Password=...
